# Generated by Django 3.2.9 on 2021-11-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelQuiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=0, max_length=254, unique=True, verbose_name='Email ID'),
            preserve_default=False,
        ),
    ]
