# Generated by Django 3.2.9 on 2021-11-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelQuiz', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email ID'),
        ),
    ]
