# Generated by Django 3.2.9 on 2021-11-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelQuiz', '0005_quizmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Authentication Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='Quiz_Name',
            field=models.CharField(default=False, max_length=20, unique=True),
        ),
    ]
