# Generated by Django 3.2.9 on 2021-11-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelQuiz', '0006_auto_20211125_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='Quiz_Name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Authentication Status'),
        ),
    ]
